name: Deploy to gh-pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        fetch-depth: 0

    - name: Set up Git identity
      run: |
        git config --global user.name "${{ github.event.head_commit.author.name }}"
        git config --global user.email "${{ github.event.head_commit.author.email }}"

    - name: Merge develop branch into gh-pages
      run: |
        git merge --no-commit --no-ff origin/develop
        git commit -m "Merge develop branch into gh-pages"

    - name: Push changes to gh-pages
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
